[[custom_groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]ğŸš€ è‡ªåŠ¨é€‰æ‹©(é«˜å€ç‡èŠ‚ç‚¹)","[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©","[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹","[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹","[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹","[]ğŸ‡¹ğŸ‡· åœŸåŒºèŠ‚ç‚¹","[]ğŸ‡¦ğŸ‡· é˜¿åŒºèŠ‚ç‚¹"]


[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "select"
rule = ["(ğŸ‡­ğŸ‡°|HK|Hongkong|é¦™æ¸¯|æ¸¯)"]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹"
type = "select"
rule = ["^(?!.*å°¼äºš).*(ğŸ‡ºğŸ‡¸|US|United States|ç¾å›½|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)"]

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹"
type = "select"
rule = ["(ğŸ‡¹ğŸ‡¼|TW|Taiwan|å°æ¹¾|å°|æ–°åŒ—|å½°åŒ–)"]


[[custom_groups]]
name = "ğŸ‡²ğŸ‡´ æ¾³é—¨èŠ‚ç‚¹"
type = "select"
rule = ["(ğŸ‡²ğŸ‡´|MO|Macao|æ¾³é—¨)"]


[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "select"
rule = ["^(?!.*åˆ©äºš).*(ğŸ‡¯ğŸ‡µ|JP|Japan|æ—¥æœ¬|æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥)"]


[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "select"
rule = ["(ğŸ‡°ğŸ‡·|KR|Korea|éŸ©å›½|KOR|é¦–å°”|éŸ©|éŸ“)"]


[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
type = "select"
rule = ["(ğŸ‡¸ğŸ‡¬|SG|Singapore|æ–°åŠ å¡|å¡|ç‹®åŸ)"]


[[custom_groups]]
name = "ğŸ‡¹ğŸ‡· åœŸåŒºèŠ‚ç‚¹"
type = "select"
rule = ["(ğŸ‡¹ğŸ‡·|TR|Turkey|å£«è€³å…¶|TÃ¼rkiye)"]


[[custom_groups]]
name = "ğŸ‡¦ğŸ‡· é˜¿åŒºèŠ‚ç‚¹"
type = "select"
rule = ["(ğŸ‡¦ğŸ‡·|AR|Argentina|é˜¿æ ¹å»·)"]


[[custom_groups]]
name = "ğŸ¥ å¥ˆé£è§†é¢‘"
type = "select"
rule = ["[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡²ğŸ‡´ æ¾³é—¨èŠ‚ç‚¹"]
#rule = ["(?i)^(?!.*([Xx]?[0-1]+\\.[0-9]+[Xx]?)).*(NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media|ğŸ‡­ğŸ‡°|HK|Hongkong|é¦™æ¸¯|ğŸ‡¹ğŸ‡¼|TW|Taiwan|å°æ¹¾|å°|æ–°åŒ—|å½°åŒ–|ğŸ‡²ğŸ‡´|MO|Macao|æ¾³é—¨|ğŸ‡¯ğŸ‡µ|JP|Japan|æ—¥æœ¬|æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥)"]


[[custom_groups]]
name = "ğŸµ TikTok"
type = "select"
rule = ["[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹(è‡ªåŠ¨)","[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ“º å“”å“©å“”å“©"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹"]


[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯Bing"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]


[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]


[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]


[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹","[]ğŸ‡¦ğŸ‡· é˜¿åŒºèŠ‚ç‚¹","[]ğŸ‡¹ğŸ‡· åœŸåŒºèŠ‚ç‚¹"]


[[custom_groups]]
name = "ğŸ’¬ OpenAi"
type = "select"
rule = ["[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]ğŸ¯ å…¨çƒç›´è¿"]


[[custom_groups]]
name = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","(ç½‘æ˜“|éŸ³ä¹|è§£é”|Music|NetEase)"]


[[custom_groups]]
name = "ğŸ“¢ è°·æ­ŒFCM"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]


[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rule = ["[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]


[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©","[]ğŸ¯ å…¨çƒç›´è¿"]


[[custom_groups]]
name = "ğŸš€ è‡ªåŠ¨é€‰æ‹©(é«˜å€ç‡èŠ‚ç‚¹)"
type = "url-test"
#rule = ["(?i)^(?!.*(ğŸ‡¦ğŸ‡¬|ğŸ‡ªğŸ‡¨|ğŸ‡µğŸ‡ª|ğŸ‡¸ğŸ‡´|ğŸ‡®ğŸ‡¸|ğŸ‡¸ğŸ‡²|ğŸ‡¬ğŸ‡§|ğŸ‡¬ğŸ‡®|ğŸ‡«ğŸ‡´|ğŸ‡¦ğŸ‡±|ğŸ‡µğŸ‡¸|)).*([Xx]?[2-9]+\\.[0-9]+[Xx]?)"]
rule = ["(?i)^(?!.*([Xx]?[0-1]+\\.[0-9]+[Xx]?)).*(ğŸ‡­ğŸ‡°|HK|Hongkong|é¦™æ¸¯|ğŸ‡¹ğŸ‡¼|TW|Taiwan|å°æ¹¾|å°|æ–°åŒ—|å½°åŒ–|ğŸ‡²ğŸ‡´|MO|Macao|æ¾³é—¨|ğŸ‡ºğŸ‡¸|US|United States|ç¾å›½|ç¾)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
timeout = 2
tolerance = 150


[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = ["(ğŸ‡­ğŸ‡°|HK|Hongkong|é¦™æ¸¯|ğŸ‡¹ğŸ‡¼|TW|Taiwan|å°æ¹¾|å°|æ–°åŒ—|å½°åŒ–|ğŸ‡²ğŸ‡´|MO|Macao|æ¾³é—¨|ğŸ‡ºğŸ‡¸|US|United States|ç¾å›½|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
timeout = 2
tolerance =150

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹(è‡ªåŠ¨)"
type = "url-test"
rule = ["(ğŸ‡­ğŸ‡°|HK|Hongkong|é¦™æ¸¯|æ¸¯)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
timeout = 2
tolerance =150

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹(è‡ªåŠ¨)"
type = "url-test"
rule = ["(ğŸ‡¹ğŸ‡¼|TW|Taiwan|å°æ¹¾|å°|æ–°åŒ—|å½°åŒ–)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
timeout = 2
tolerance =150

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹(è‡ªåŠ¨)"
type = "url-test"
rule = ["^(?!.*å°¼äºš).*(ğŸ‡ºğŸ‡¸|US|United States|ç¾å›½|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
timeout = 2
tolerance =150

[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]


[[custom_groups]]
name = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]


[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = ["[]REJECT","[]DIRECT"]


