[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/LocalAreaNetwork.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/UnBan.list"
[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "rules/ACL4SSR/Clash/BanAD.list"
[[rulesets]]
group = "ğŸƒ åº”ç”¨å‡€åŒ–"
ruleset = "rules/ACL4SSR/Clash/BanProgramAD.list"
[[rulesets]]
group = "ğŸ“¢ è°·æ­ŒFCM"
ruleset = "rules/ACL4SSR/Clash/Ruleset/GoogleFCM.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Ruleset/GoogleCN.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Ruleset/SteamCN.list"
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯Bing"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Bing.list"
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "rules/ACL4SSR/Clash/Ruleset/OneDrive.list"
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Microsoft.list"
[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Apple.list"
[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Telegram.list"
[[rulesets]]
group = "ğŸ’¬ OpenAi"
ruleset = "rules/ACL4SSR/Clash/Ruleset/OpenAi.list"
[[rulesets]]
group = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
ruleset = "rules/ACL4SSR/Clash/Ruleset/NetEaseMusic.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Epic.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Origin.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Sony.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Steam.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Nintendo.list"
[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "rules/ACL4SSR/Clash/Ruleset/YouTube.list"
[[rulesets]]
group = "ğŸ¥ å¥ˆé£è§†é¢‘"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Netflix.list"
[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Bahamut.list"
[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "rules/ACL4SSR/Clash/Ruleset/BilibiliHMT.list"
[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Bilibili.list"
[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "rules/ACL4SSR/Clash/ChinaMedia.list"
[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "rules/ACL4SSR/Clash/DouYin.list"
[[rulesets]]
group = "ğŸµ TikTok"
ruleset = "rules/ACL4SSR/Clash/Ruleset/TikTok.list"
[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "rules/ACL4SSR/Clash/ProxyMedia.list"
[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/ACL4SSR/Clash/ProxyGFWlist.list"
# [[rulesets]]
# group = "ğŸ¯ å…¨çƒç›´è¿"
# ruleset = "rules/ACL4SSR/Clash/ChinaIp.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/ChinaDomain.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/ChinaCompanyIp.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Download.list"
# [[rulesets]]
# group = "ğŸ¯ å…¨çƒç›´è¿
# ruleset = "[]GEOIP,LAN"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"
[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
# è®¾ç½®è§„åˆ™æ ‡å¿—ä½
