# -æ‹¦æˆªéƒ¨åˆ†-
[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "rules/Clash/ACL4SSR/BanAD.list"
[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "rules/Clash/ACL4SSR/BanProgramAD.list"
[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "rules/Clash/ACL4SSR/BanEasyListChina.list"
# -å¤–å›½å…¬å¸-
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯Bing"
ruleset = "rules/Clash/Bing/Bing.list"
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "rules/Clash/OneDrive/OneDrive.list"
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "rules/Clash/Microsoft/Microsoft.list"
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "rules/Clash/MicrosoftEdge/MicrosoftEdge.list"
[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "rules/Clash/Apple/Apple.list"
[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "rules/Clash/Telegram/Telegram.list"
# -æ¸¸æˆå¹³å°-
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/Clash/Steam/Steam.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/Clash/Epic/Epic.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/Clash/Origin/Origin.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/Clash/EA/EA.list"
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/Clash/Blizzard/Blizzard.list"
# -è§†é¢‘éŸ³ä¹-
[[rulesets]]
group = "ğŸ¥ å¥ˆé£è§†é¢‘"
ruleset = "rules/Clash/Netflix/Netflix.list"
[[rulesets]]
group = "ğŸµ TikTok"
ruleset = "rules/Clash/TikTok/TikTok.list"
[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "rules/Clash/YouTube/YouTube.list"
[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "rules/Clash/YouTubeMusic/YouTubeMusic.list"
[[rulesets]]
group = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
ruleset = "rules/Clash/NetEaseMusic/NetEaseMusic.list"
[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "rules/Clash/BiliBili/BiliBili.list"
[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "rules/Clash/BiliBiliIntl/BiliBiliIntl.list"
[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "rules/Clash/Bahamut/Bahamut.list"
[[rulesets]]
group = "ğŸ“¢ è°·æ­ŒFCM"
ruleset = "rules/Clash/GoogleFCM/GoogleFCM.list"
# -äººå·¥æ™ºèƒ½-
[[rulesets]]
group = "ğŸ’¬ OpenAi"
ruleset = "rules/Clash/OpenAI/OpenAI.list"
# -å‰©ä½™å¼ºåˆ¶ç›´è¿çš„ç½‘ç«™-
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/Clash/Lan/Lan.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/Clash/ChinaMaxNoIP/ChinaMaxNoIP.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/Clash/ChinaDNS/ChinaDNS.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/Clash/ChinaMedia/ChinaMedia.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/Clash/Download/Download.list"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/Clash/SteamCN/SteamCN.list"
# -å‰©ä½™å¼ºåˆ¶ä»£ç†çš„ç½‘ç«™-
[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/Clash/Proxy/Proxy.list"
[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/Clash/GitHub/GitHub.list"
[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/Clash/MySelf/SubConverter.list"
# -GEOPIPåŸŸåDNSè§£æ å›½å†…IPåˆ¤å®š-
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,LAN,no-resolve"
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN,no-resolve"
# -æœªå‘½ä¸­å…œåº•-
[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
# è®¾ç½®è§„åˆ™æ ‡å¿—ä½
